name: stratosfy_scanner
description: A flutter package to scan beacons from stratosfy.io
version: 1.0.0
homepage: https://stratosfy.io

environment:
  sdk: '>=2.12.0 <4.0.0'
  flutter: ">=1.10.0"

dependencies:
  flutter:
    sdk: flutter
  convert: ^3.1.1
  geolocator: ^11.0.0
  permission_handler: ^11.3.0

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  plugin:
    platforms:
      android:
        package: io.stratosfy.stratosfy_scanner
        pluginClass: StratosfyScannerPlugin
      ios:
        pluginClass: StratosfyScannerPlugin
